import type { CatalogData, CatalogProduct, CatalogBrand } from "./types";

// Catalog data is loaded from a static JSON file generated by the export script
let _cache: CatalogData | null = null;

async function loadCatalog(): Promise<CatalogData> {
  if (_cache) return _cache;

  // In production, this reads from the bundled JSON
  // Run `npm run export-catalog` to regenerate before deploy
  const data = (await import("@/data/catalog.json")) as unknown as CatalogData;
  _cache = data;
  return data;
}

export async function getAllProducts(includeDrafts = false): Promise<CatalogProduct[]> {
  const catalog = await loadCatalog();
  if (includeDrafts) return catalog.products;
  return catalog.products.filter((p) => !p.is_draft);
}

export async function getProductBySlug(slug: string): Promise<CatalogProduct | null> {
  const catalog = await loadCatalog();
  return catalog.products.find((p) => p.slug === slug) ?? null;
}

export async function getAllBrands(): Promise<CatalogBrand[]> {
  const catalog = await loadCatalog();
  return catalog.brands;
}

export async function getAllCategories(): Promise<string[]> {
  const catalog = await loadCatalog();
  const cats = new Set(catalog.products.map((p) => p.category).filter(Boolean));
  return Array.from(cats).sort();
}

export async function getAllTags(): Promise<string[]> {
  const catalog = await loadCatalog();
  const tags = new Set(catalog.products.flatMap((p) => p.category_tags));
  return Array.from(tags).sort();
}

export function getScoreColor(score: number | null): string {
  if (score === null) return "text-muted";
  if (score >= 75) return "text-accent";
  if (score >= 50) return "text-warning";
  return "text-danger";
}

export function getGradeClass(grade: string | null): string {
  if (!grade) return "";
  const g = grade.toLowerCase();
  if (g.startsWith("a")) return "grade-a";
  if (g.startsWith("b")) return "grade-b";
  if (g.startsWith("c")) return "grade-c";
  return "grade-d";
}
