/**
 * GENERATED by scripts/extract-shelf.mjs — do not hand-edit.
 *
 * One product from each of the six catalogs, as the mockup's shelf has them.
 * Images are written beside this as files under public/console-shelf.
 *
 * Two of the six carry no score on purpose: a mask and a mattress share no
 * attribute one number could rank, so those catalogs compare inside a category
 * and the card shows the price band the catalog actually holds.
 */
export interface ShelfCard {
  key: string;
  catalog: string;
  name: string;
  brand: string;
  meta: string | null;
  /** null where the catalog has no cross-category number. */
  score: number | null;
  /** Shown instead of a score, where there is none. */
  price: string | null;
  count: number | null;
  unmerged: boolean;
  proposed: boolean;
  image: string;
}

export const SHELF_CARDS: ShelfCard[] = [
  {
    "key": "supp",
    "catalog": "Supplements",
    "name": "Creatine",
    "brand": "Thorne",
    "meta": "Creatine",
    "score": 98,
    "price": null,
    "count": 319,
    "unmerged": false,
    "proposed": false,
    "image": "/console-shelf/supp.webp"
  },
  {
    "key": "food",
    "catalog": "Branded food",
    "name": "Extra Virgin Olive Oil",
    "brand": "Blueprint",
    "meta": "Oils & Fats",
    "score": 97,
    "price": null,
    "count": 10,
    "unmerged": false,
    "proposed": false,
    "image": "/console-shelf/food.webp"
  },
  {
    "key": "care",
    "catalog": "Personal care",
    "name": "Renewing SA Cleanser",
    "brand": "CeraVe",
    "meta": "cleanser",
    "score": 92,
    "price": null,
    "count": 548,
    "unmerged": false,
    "proposed": false,
    "image": "/console-shelf/care.webp"
  },
  {
    "key": "body",
    "catalog": "Body",
    "name": "Body Scan",
    "brand": "Withings",
    "meta": "Body Composition",
    "score": null,
    "price": "$499.95",
    "count": 10,
    "unmerged": false,
    "proposed": true,
    "image": "/console-shelf/body.webp"
  },
  {
    "key": "fit",
    "catalog": "Fitness",
    "name": "SelectTech 552 Adjustable Dumbbells",
    "brand": "Bowflex",
    "meta": "free_weights",
    "score": null,
    "price": "$350–430",
    "count": 105,
    "unmerged": false,
    "proposed": false,
    "image": "/console-shelf/fit.webp"
  },
  {
    "key": "sleep",
    "catalog": "Sleep",
    "name": "Sleep Mask",
    "brand": "Manta",
    "meta": "Sleep Masks",
    "score": null,
    "price": "$35–45",
    "count": 552,
    "unmerged": true,
    "proposed": false,
    "image": "/console-shelf/sleep.webp"
  }
];
