/**
 * GENERATED by scripts/extract-panel.mjs — do not hand-edit.
 *
 * The demo account's blood panel, lifted from public/v2/index.html so section
 * 03 renders the same numbers the demo does rather than a second copy of them.
 * Every number on the page is derived from `systems` — see console-panel.tsx
 * — so nothing shown can drift from the rows underneath it.
 *
 * These are an authored account, not a person. The page says so.
 */
export interface PanelSystem {
  k: string;
  name: string;
  /** Where this system is now, 0-100. */
  score: number;
  /** Where optimal is, 0-100. */
  opt: number;
  /** Its weight in the overall score. */
  w: number;
  /** Its move since the previous panel. */
  d: number;
  /** The markers behind it, in one line. */
  lead: string;
}

export interface PanelData {
  date: string;
  prev: string;
  markers: number;
  systems: PanelSystem[];
  acted: { k: string; did: string }[];
}

export const CONSOLE_PANEL: PanelData = {
  "date": "12 Aug",
  "prev": "14 Apr",
  "markers": 42,
  "systems": [
    {
      "k": "cardio",
      "name": "Cardiovascular",
      "score": 66,
      "opt": 85,
      "w": 20,
      "d": 1,
      "lead": "ApoB 94 mg/dL · optimal is under 80"
    },
    {
      "k": "metab",
      "name": "Metabolic",
      "score": 82,
      "opt": 90,
      "w": 18,
      "d": 3,
      "lead": "HbA1c 5.1% · fasting insulin 5.4"
    },
    {
      "k": "fitness",
      "name": "Fitness capacity",
      "score": 58,
      "opt": 85,
      "w": 16,
      "d": -1,
      "lead": "VO2 max 42 · grip 47 kg"
    },
    {
      "k": "body",
      "name": "Body composition",
      "score": 70,
      "opt": 88,
      "w": 14,
      "d": 2,
      "lead": "18.4% fat · waist-to-height 0.47"
    },
    {
      "k": "inflam",
      "name": "Inflammation",
      "score": 88,
      "opt": 92,
      "w": 12,
      "d": 6,
      "lead": "hs-CRP 0.6 mg/L · homocysteine 9.1"
    },
    {
      "k": "horm",
      "name": "Hormonal / thyroid",
      "score": 74,
      "opt": 88,
      "w": 10,
      "d": 0,
      "lead": "Free T3 3.1 · testosterone 612"
    },
    {
      "k": "sleeparch",
      "name": "Sleep architecture",
      "score": 61,
      "opt": 86,
      "w": 10,
      "d": 4,
      "lead": "Deep 58 min · HRV 41 ms"
    }
  ],
  "acted": [
    {
      "k": "inflam",
      "did": "Added omega-3 and curcumin, daily"
    },
    {
      "k": "sleeparch",
      "did": "Magnesium moved 90 minutes earlier"
    },
    {
      "k": "metab",
      "did": "Ten minute walk after dinner"
    },
    {
      "k": "horm",
      "did": "Nothing aimed here"
    },
    {
      "k": "fitness",
      "did": "Two sessions a week became one"
    }
  ]
};
