import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    // Vercel's image optimizer is metered (1k source images/mo on Hobby).
    // The desktop image pipeline already emits pre-optimized WebP + thumbs,
    // so routing through /_next/image just burns quota and returns 402s
    // once exhausted. Serve the files directly instead.
    unoptimized: true,
  },

  /**
   * Keep the 322 MB of product images OUT of every serverless function bundle.
   * Next's file tracer was pulling all of `public/images` (~309 MB) into the 14
   * dynamic routes (brands, supplements, ingredients, …), tripping Vercel's
   * "Max serverless function size of 250 MB uncompressed exceeded" on every
   * deploy. Those files are static assets served directly by the CDN — NO route
   * reads them via `fs` (verified: the only fs reads are research/.tsx content,
   * and OG routes are text-only `next/og`), so excluding them from the function
   * traces is safe and does not affect the separately-uploaded static assets.
   */
  outputFileTracingExcludes: {
    "*": ["public/images/**", "public/food-assets/**", "public/recipe-assets/**"],
  },

  /**
   * Redirect any legacy / Google-indexed catalog URLs to the app subdomain.
   * The per-product catalog lives on app.formulate-health.app — not landing —
   * but historical canonical tags accidentally pointed Google at
   * formulate-health.app/catalog/*, so real visitors from search results were
   * hitting our 404 page. These 301s fix inbound links instantly; Google will
   * update its index once it re-crawls the corrected canonical on destination.
   *
   * NOTE: /brands and /brands/:slug* are NOT redirected — the SEO-facing brand
   * hub pages live here on the landing site (see src/app/brands/). The webapp
   * has its own /brands view for logged-in users; different surface, same data.
   */
  async redirects() {
    return [
      /**
       * Social-card URLs from before the route-group split.
       *
       * Adding a second root layout (for `<html lang>` on /es) forced Next to
       * disambiguate the root metadata images, so `/opengraph-image` became
       * `/opengraph-image-35z9bs`. New shares are fine — the meta tags point at
       * the new path — but cards already cached by Slack, X, LinkedIn et al.
       * still request the old one and would get a 404 and a blank preview.
       *
       * ⚠ The suffix is generated by Next from the route structure. If the app
       * directory is reorganised again it can change, and these redirects will
       * silently point at nothing. Re-check them by curling `/` and reading the
       * og:image meta tag whenever src/app's top level moves.
       */
      { source: "/opengraph-image", destination: "/opengraph-image-35z9bs", permanent: false },
      { source: "/twitter-image", destination: "/twitter-image-35z9bs", permanent: false },
      {
        source: "/catalog",
        destination: "https://app.formulate-health.app/catalog",
        permanent: true,
      },
      {
        source: "/catalog/:slug*",
        destination: "https://app.formulate-health.app/catalog/:slug*",
        permanent: true,
      },
      {
        source: "/stack",
        destination: "https://app.formulate-health.app/stack",
        permanent: true,
      },
    ];
  },

  /**
   * PostHog reverse proxy. Ad blockers blocklist *.posthog.com, silently
   * dropping 10-25% of analytics events. Routing ingestion through our own
   * domain (/ingest/*) makes it first-party and dodges the blocklists.
   * posthog.ts points api_host at "/ingest". US Cloud destinations.
   */
  async rewrites() {
    return [
      {
        source: "/ingest/static/:path*",
        destination: "https://us-assets.i.posthog.com/static/:path*",
      },
      {
        source: "/ingest/:path*",
        destination: "https://us.i.posthog.com/:path*",
      },
    ];
  },
  // PostHog sends trailing-slash-sensitive paths; don't let Next 308-redirect them.
  skipTrailingSlashRedirect: true,
};

export default nextConfig;
