"use client";

/**
 * The shelf — one product from each of the six catalogs.
 *
 * Section 01 says "every item comes back scored". Nothing on the page showed
 * that, so the claim sat on trust. These are real products with their real
 * numbers.
 *
 * WHY ONE PER CATALOG RATHER THAN THE SIX BEST. The shelf that was here took
 * the top-scoring item with a photograph from each of this site's own three
 * catalogs, which gave two supplements, two whole foods and two recipes. Good
 * cards, wrong argument: six things from three catalogs says "we score
 * supplements and food". One item from each of six says the thing that is
 * actually surprising — that a capsule, a bottle of olive oil, a cleanser, a
 * scale, a pair of dumbbells and a sleep mask are scored by one product.
 *
 * TWO OF THEM CARRY NO SCORE, AND THAT IS THE HONEST PART. A mask and a
 * mattress share no attribute one number could rank, so those catalogs compare
 * within a category and the card shows the price band the catalog really
 * holds. The note under the shelf is derived from the cards themselves, so it
 * cannot describe a row that is not there.
 *
 * ONE CARD IS A PROPOSAL AND SAYS SO. Body measurement has no catalog in any
 * repository — the device was compiled for the mockup. It is kept because the
 * pillar is real and the shelf is about breadth, and it is labelled PROPOSED
 * on the card and again in the note. If that is too generous a claim, the fix
 * is to drop the card, not to quieten the label.
 *
 * The cards are generated by scripts/extract-shelf.mjs; images are files under
 * public/console-shelf rather than the demo's inline data URIs.
 */
import { SHELF_CARDS as CARDS } from "@/lib/console-shelf-cards";

/** The score, as a ring on the picture's corner. */
function Ring({ score }: { score: number }) {
  const R = 12;
  const TAU = 2 * Math.PI * R;
  const color = score >= 90 ? "#8ee8ab" : score >= 75 ? "#cfe88e" : "#ffc27a";
  return (
    <span className="cn-meter">
      <svg viewBox="0 0 30 30" width="30" height="30" aria-hidden="true">
        <circle cx="15" cy="15" r={R} fill="none" stroke="rgba(255,255,255,.14)" strokeWidth="3" />
        <circle
          cx="15"
          cy="15"
          r={R}
          fill="none"
          stroke={color}
          strokeWidth="3"
          strokeLinecap="round"
          strokeDasharray={`${((TAU * score) / 100).toFixed(1)} ${TAU.toFixed(1)}`}
          transform="rotate(-90 15 15)"
        />
      </svg>
      <i style={{ color }}>{score}</i>
    </span>
  );
}

/** The note, read off the cards. Nothing here is typed. */
function note() {
  const unscored = CARDS.filter((c) => c.score == null);
  if (!unscored.length) return null;
  const names = unscored.map((c) => c.catalog);
  const last = names.pop();
  const built = unscored.find((c) => c.unmerged);
  const proposed = unscored.find((c) => c.proposed);
  return (
    <p className="cn-shelfnote">
      <b>
        {names.join(", ")} and {last} carry no score
      </b>{" "}
      — a mask and a mattress share no attribute one number could rank, so each
      is compared inside its own category
      {built && built.count
        ? `. ${built.catalog}'s ${built.count.toLocaleString()} are built, not merged`
        : ""}
      {proposed && proposed.count
        ? `; the ${proposed.count} ${proposed.catalog.toLowerCase()} devices are a proposal`
        : ""}
      .
    </p>
  );
}

export function ConsoleShelf() {
  return (
    <div className="cn-shelf">
      {CARDS.map((c) => (
        <div className="cn-card" key={c.key}>
          <span className={`cn-cat ${c.proposed ? "prop" : ""}`}>
            {c.catalog}
            {c.proposed ? " · proposed" : ""}
          </span>
          <span className="cn-shot">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={c.image} alt="" loading="lazy" decoding="async" />
            {c.score != null ? (
              <Ring score={c.score} />
            ) : (
              <span className="cn-price mono">{c.price}</span>
            )}
          </span>
          <span className="cn-nm">{c.name}</span>
          <span className="cn-cardsub">{c.brand}</span>
        </div>
      ))}
      {note()}
    </div>
  );
}
