import type { Metadata } from "next";
import Link from "next/link";
import { withUtm } from "@/lib/app-url";

export const metadata: Metadata = {
  title: "About Formulate — Evidence-Based Supplement Scoring",
  description:
    "Formulate is an independent supplement scoring platform. We score every supplement against clinical research — no sponsorships, no paid placements, no editorial favoritism.",
  alternates: { canonical: "https://formulate-health.app/about" },
  openGraph: {
    title: "About Formulate — Evidence-Based Supplement Scoring",
    description:
      "Independent supplement scoring. Every product rated 50–100 against clinical research. No sponsorships.",
    type: "website",
  },
};

const PRINCIPLES = [
  {
    title: "No sponsorships, ever",
    desc: "We do not accept payment to list, rank, or feature products. We earn a small affiliate commission on some outbound purchase links, but that never influences scoring. The algorithm doesn't care who pays.",
  },
  {
    title: "Deterministic scoring",
    desc: "Every score is generated by the same algorithm on the same data. Two analysts running our engine get the same number. No editorial judgment, no reviewer bias — just consistent methodology.",
  },
  {
    title: "Source-of-truth transparency",
    desc: "Every product page shows the full score breakdown, the evidence tier for each claim, and the reasoning behind dose and form decisions. If you disagree with a score, you can see exactly why we gave it.",
  },
  {
    title: "Versioned evidence base",
    desc: "Clinical research updates quarterly. When a new meta-analysis shifts the evidence, we rescore the affected products. Nothing is frozen — the catalog keeps current with the science.",
  },
];

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "AboutPage",
  url: "https://formulate-health.app/about",
  name: "About Formulate",
  description:
    "Formulate is an independent supplement scoring platform that rates every supplement against clinical research.",
  mainEntity: {
    "@type": "Organization",
    "@id": "https://formulate-health.app/#organization",
    name: "Formulate",
    url: "https://formulate-health.app",
    logo: {
      "@type": "ImageObject",
      url: "https://formulate-health.app/logo.png",
      width: 512,
      height: 512,
    },
    description:
      "Evidence-based supplement scoring platform. Every supplement rated 50–100 against clinical research. No sponsorships.",
    sameAs: ["https://app.formulate-health.app"],
    foundingDate: "2025",
  },
};

export default function AboutPage() {
  return (
    <div className="pt-24 pb-20 px-6">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      <div className="max-w-[760px] mx-auto">
        {/* Breadcrumb */}
        <nav className="flex items-center gap-2 text-xs text-muted mb-8">
          <Link href="/" className="hover:text-text transition-colors">
            Home
          </Link>
          <span>/</span>
          <span className="text-text/60">About</span>
        </nav>

        <div className="text-xs font-bold tracking-[2px] uppercase text-accent mb-3">
          About
        </div>
        <h1 className="text-[clamp(28px,4vw,44px)] font-extrabold tracking-[-1px] leading-[1.15] mb-4">
          We score supplements so you don&apos;t have to guess
        </h1>
        <p className="text-base text-muted leading-relaxed mb-10 max-w-[620px]">
          The supplement industry runs on marketing, sponsorships, and vague
          claims. Formulate runs on clinical evidence, third-party testing data,
          and a scoring algorithm anyone can inspect. Every product gets a number
          from 50 to 100. That number means something.
        </p>

        {/* Why we exist */}
        <section className="mb-14">
          <h2 className="text-xl font-bold mb-4">Why we built this</h2>
          <div className="space-y-4 text-[15px] text-muted leading-relaxed">
            <p>
              Walk into any supplement store and you&apos;ll see 200 brands
              selling the same ingredient. The labels look identical. The claims
              look identical. But the actual products are wildly different —
              different doses, different forms, different manufacturing quality,
              different evidence bases.
            </p>
            <p>
              We got tired of seeing friends and family pay premium prices for
              underdosed multivitamins, poorly-absorbed magnesium oxide, and
              oxidized fish oil. So we built a scoring system that makes the
              differences visible.
            </p>
            <p>
              Formulate is independent — we take no money from supplement brands
              to list, feature, or rank them. The scoring is deterministic: the
              same algorithm runs on every product, the weights are public, and
              the reasoning is shown for every score. See our{" "}
              <Link href="/methodology" className="text-accent hover:underline">
                methodology page
              </Link>{" "}
              for the full breakdown.
            </p>
          </div>
        </section>

        {/* Principles */}
        <section className="mb-14">
          <h2 className="text-xl font-bold mb-6">How we work</h2>
          <div className="space-y-4">
            {PRINCIPLES.map((p) => (
              <div key={p.title} className="p-5 rounded-xl bg-surface border border-border">
                <h3 className="text-sm font-bold text-text mb-2">{p.title}</h3>
                <p className="text-sm text-muted leading-relaxed">{p.desc}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Who we are */}
        <section className="mb-14">
          <h2 className="text-xl font-bold mb-4">Who we are</h2>
          <p className="text-[15px] text-muted leading-relaxed mb-4">
            Formulate is built and maintained by the Formulate Team — a group of
            developers, researchers, and data analysts focused on making the
            supplement industry legible. We&apos;re not doctors, and we
            don&apos;t give medical advice. We aggregate the best available
            evidence and turn it into a score you can actually use.
          </p>
          <p className="text-[15px] text-muted leading-relaxed">
            Have a question about how we scored something? Found an error? Want
            to suggest a product we should add to the catalog?{" "}
            <a
              href="mailto:support@formulate-health.app"
              className="text-accent hover:underline"
            >
              Email us
            </a>
            . We read everything.
          </p>
        </section>

        {/* Affiliate disclosure */}
        <section className="mb-14">
          <h2 className="text-xl font-bold mb-4">Affiliate disclosure</h2>
          <p className="text-sm text-muted leading-relaxed">
            When you buy a supplement through an outbound link on Formulate, we
            may earn a small commission from the retailer (typically Amazon,
            iHerb, or a brand&apos;s own site). This commission comes from the
            retailer&apos;s margin and does not increase your price. It does not
            influence our scoring — brands cannot pay us to raise their score,
            and we do not prioritize products based on commission rate. Full
            disclosure on our{" "}
            <Link href="/disclosure" className="text-accent hover:underline">
              disclosure page
            </Link>
            .
          </p>
        </section>

        {/* CTA */}
        <div className="p-8 rounded-2xl bg-surface border border-accent/20 text-center">
          <h3 className="text-lg font-bold mb-2">Ready to see scores?</h3>
          <p className="text-sm text-muted mb-5 max-w-[440px] mx-auto">
            230+ supplements scored. Free, no account required.
          </p>
          <a
            href={withUtm("https://app.formulate-health.app/catalog", {
              source: "landing",
              campaign: "about_cta",
            })}
            className="inline-flex items-center gap-2 px-6 py-3 rounded-xl text-sm font-semibold bg-accent text-bg hover:bg-[#00ffb3] transition-all"
          >
            Browse the catalog →
          </a>
        </div>
      </div>
    </div>
  );
}
