import type { Metadata } from "next";
import Link from "next/link";
import { withUtm } from "@/lib/app-url";

export const metadata: Metadata = {
  title: "Methodology — How Formulate Scores Supplements",
  description:
    "Every Formulate score is built from six pillars: evidence, manufacturing, dose, bioavailability, transparency, and safety. No sponsorships, just data.",
  alternates: { canonical: "https://formulate-health.app/methodology" },
  openGraph: {
    title: "How Formulate Scores Supplements — Methodology",
    description:
      "Every supplement scored 50–100 across six pillars. Transparent, evidence-based, no sponsorships.",
    type: "article",
  },
};

const PILLARS = [
  {
    weight: "25%",
    color: "text-green-400",
    name: "Clinical Evidence",
    desc: "Quality and quantity of peer-reviewed human research supporting the ingredient, its dose, and its claimed outcome. Meta-analyses and RCTs score higher than animal studies or anecdote.",
  },
  {
    weight: "20%",
    color: "text-blue-400",
    name: "Manufacturing Quality",
    desc: "Third-party certifications (NSF, USP, Informed Sport), facility audits, and batch-level testing. A product is only as good as its factory.",
  },
  {
    weight: "20%",
    color: "text-cyan-400",
    name: "Dose Accuracy",
    desc: "Does the serving actually match the evidence-based range for the claimed benefit? Underdosed and overdosed products both lose points.",
  },
  {
    weight: "15%",
    color: "text-amber-400",
    name: "Bioavailability",
    desc: "Form, chelation, and delivery method. Magnesium glycinate and magnesium oxide are not the same supplement — and we score them accordingly.",
  },
  {
    weight: "10%",
    color: "text-purple-400",
    name: "Label Transparency",
    desc: "Full ingredient disclosure, no proprietary blends hiding doses, verified COAs on request. If a brand won't tell you what's in it, we penalize it.",
  },
  {
    weight: "10%",
    color: "text-red-400",
    name: "Safety Profile",
    desc: "Known interactions, contraindications, heavy-metal testing, and exposure to fillers or allergens. A supplement that works but hurts still loses points.",
  },
];

const SCORE_BANDS = [
  { range: "90–100", label: "Exceptional", color: "text-green-400", desc: "Best-in-class on every pillar. Evidence-backed, rigorously manufactured, transparent." },
  { range: "80–89", label: "Strong", color: "text-blue-400", desc: "Solid across the board with minor gaps. Safe default choices." },
  { range: "70–79", label: "Decent", color: "text-cyan-400", desc: "Works, but has room to improve. Often a weaker form or less transparency." },
  { range: "60–69", label: "Below Average", color: "text-amber-400", desc: "Real concerns — wrong form, low dose, or poor manufacturing track record." },
  { range: "50–59", label: "Weak", color: "text-red-400", desc: "Meaningful problems with the product. Consider alternatives." },
];

const FAQS = [
  {
    q: "Why doesn't anything score below 50?",
    a: "We don't list products we wouldn't be comfortable recommending at all. The 50–100 scale reflects the range of products that passed our screening. Products that fail safety or legitimacy checks don't get a score — they don't get listed.",
  },
  {
    q: "Do brands pay to be on Formulate?",
    a: "No. We do not accept payment to list, rank, or feature any product. We may earn affiliate commissions from qualifying purchases through outbound links, but this does not affect scoring. The same algorithm runs on every product in the catalog.",
  },
  {
    q: "How often are scores updated?",
    a: "Ingredient evidence is re-evaluated quarterly based on new meta-analyses and clinical trials. Product-specific data (formulation changes, new certifications, recalls) triggers an immediate rescore when detected.",
  },
  {
    q: "Why does one supplement score higher than another with identical ingredients?",
    a: "Two products can have the same active ingredients but very different scores because of form (e.g., magnesium glycinate vs oxide), dose accuracy, third-party testing, and manufacturing transparency. Our methodology weighs these explicitly.",
  },
  {
    q: "Can I see the raw scoring data?",
    a: "Yes. Every product page shows the full score breakdown by pillar, the specific evidence tier for each claimed benefit, and the reasoning behind dose and form scores. Full transparency is non-negotiable.",
  },
  {
    q: "Who builds and maintains the scoring engine?",
    a: "The Formulate Team — a group of developers, researchers, and analysts who build the platform and curate the evidence base. Scores are generated by a deterministic algorithm, not editorial judgment, so two reviewers running it get the same number.",
  },
];

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebPage",
      "@id": "https://formulate-health.app/methodology",
      url: "https://formulate-health.app/methodology",
      name: "How Formulate Scores Supplements — Methodology",
      description:
        "Every Formulate score is built from six pillars: evidence, manufacturing, dose, bioavailability, transparency, and safety.",
      isPartOf: { "@id": "https://formulate-health.app/#website" },
      about: { "@id": "https://formulate-health.app/#organization" },
    },
    {
      "@type": "FAQPage",
      mainEntity: FAQS.map((f) => ({
        "@type": "Question",
        name: f.q,
        acceptedAnswer: { "@type": "Answer", text: f.a },
      })),
    },
  ],
};

export default function MethodologyPage() {
  return (
    <div className="pt-24 pb-20 px-6">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      <div className="max-w-[820px] mx-auto">
        {/* Breadcrumb */}
        <nav className="flex items-center gap-2 text-xs text-muted mb-8">
          <Link href="/" className="hover:text-text transition-colors">
            Home
          </Link>
          <span>/</span>
          <span className="text-text/60">Methodology</span>
        </nav>

        <div className="text-xs font-bold tracking-[2px] uppercase text-accent mb-3">
          How We Score
        </div>
        <h1 className="text-[clamp(28px,4vw,44px)] font-extrabold tracking-[-1px] leading-[1.15] mb-4">
          Every supplement scored 50–100 across six pillars
        </h1>
        <p className="text-base text-muted leading-relaxed mb-12 max-w-[640px]">
          Formulate scores are deterministic and transparent. The same algorithm
          runs on every product, the weights are public, and the evidence base is
          versioned. No sponsorships, no editorial favoritism.
        </p>

        {/* Pillars */}
        <section className="mb-14">
          <h2 className="text-xl font-bold mb-6">The six pillars</h2>
          <div className="space-y-3">
            {PILLARS.map((p) => (
              <div
                key={p.name}
                className="flex items-start gap-4 p-5 rounded-xl bg-surface border border-border"
              >
                <div className="shrink-0 w-16 text-center">
                  <div className={`text-xl font-black ${p.color}`}>{p.weight}</div>
                </div>
                <div>
                  <div className="text-sm font-bold text-text mb-1">{p.name}</div>
                  <p className="text-sm text-muted leading-relaxed">{p.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Score bands */}
        <section className="mb-14">
          <h2 className="text-xl font-bold mb-6">What the score means</h2>
          <div className="rounded-xl bg-surface border border-border p-5 space-y-3">
            {SCORE_BANDS.map((b) => (
              <div key={b.range} className="flex items-start gap-4">
                <div className="shrink-0 w-24">
                  <div className={`font-mono font-bold text-sm ${b.color}`}>{b.range}</div>
                  <div className={`text-xs font-semibold ${b.color}`}>{b.label}</div>
                </div>
                <p className="text-sm text-muted leading-relaxed flex-1">{b.desc}</p>
              </div>
            ))}
          </div>
        </section>

        {/* FAQ */}
        <section className="mb-14">
          <h2 className="text-xl font-bold mb-6">Frequently asked questions</h2>
          <div className="space-y-4">
            {FAQS.map((f) => (
              <div key={f.q} className="p-5 rounded-xl bg-surface border border-border">
                <h3 className="text-sm font-bold text-text mb-2">{f.q}</h3>
                <p className="text-sm text-muted leading-relaxed">{f.a}</p>
              </div>
            ))}
          </div>
        </section>

        {/* CTA */}
        <div className="p-8 rounded-2xl bg-surface border border-accent/20 text-center">
          <h3 className="text-lg font-bold mb-2">See it in action</h3>
          <p className="text-sm text-muted mb-5 max-w-[440px] mx-auto">
            Every product page shows the full pillar breakdown, the evidence tier for each claim, and the exact reasoning behind the number.
          </p>
          <a
            href={withUtm("https://app.formulate-health.app/methodology", {
              source: "landing",
              campaign: "methodology_deep_link",
            })}
            className="inline-flex items-center gap-2 px-6 py-3 rounded-xl text-sm font-semibold bg-accent text-bg hover:bg-[#00ffb3] transition-all"
          >
            Explore the full methodology →
          </a>
        </div>
      </div>
    </div>
  );
}
