#!/usr/bin/env node
/**
 * Pull the eight trackable marks out of the demo and into a module the React
 * landing can render.
 *
 * WHY GENERATED. The marks are the duotone set — sizeable inline SVG with
 * their own gradients and filters — and they already exist, once, inside
 * public/v2/index.html. Hand-copying eight of them into a .tsx would create a
 * second copy that looks identical on the day it is made and diverges from
 * then on, which is the failure this repo has a standing rule about. So this
 * reads the registry and writes the module, and running it again is how the
 * module gets fixed.
 *
 * THE ID PROBLEM. Each mark's <defs> uses short global ids (ca2, cb3, gs1).
 * Two SVGs sharing one id on a page means the second silently borrows the
 * first's gradient — a bug that renders as "some of the marks are the wrong
 * colour" and is almost impossible to read backwards. So every id is
 * rewritten with a per-mark prefix, and the script fails if any survive
 * unprefixed or if two marks still collide.
 *
 *     node scripts/extract-marks.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "public/v2/index.html");
const OUT = join(ROOT, "src/lib/console-marks.ts");

/** The wall, exactly as the demo builds it (its `WALL` array). */
const WALL = [
  ["capsule", "SUPPS"],
  ["meal", "MEALS"],
  ["glass", "WATER"],
  ["dumbbell", "TRAIN"],
  ["sauna", "SAUNA"],
  ["moon", "SLEEP"],
  ["cabin", "BODY"],
  ["care", "SKIN"],
];

const html = readFileSync(SRC, "utf8");
const start = html.indexOf("var MARKS = {");
if (start === -1) throw new Error("MARKS registry not found in public/v2/index.html");

/** Read one size's SVG string for a key out of the registry text. */
function svgFor(key, size) {
  const at = html.indexOf(`${key}: {`, start);
  if (at === -1) throw new Error(`mark "${key}" is not in the registry`);
  const re = new RegExp(`${size}:'((?:[^'\\\\]|\\\\.)*)'`, "g");
  re.lastIndex = at;
  const m = re.exec(html);
  if (!m || m.index > at + 40000) throw new Error(`mark "${key}" has no ${size}: entry`);
  return m[1];
}

const seenIds = new Set();
const marks = [];

for (const [key, label] of WALL) {
  let svg = svgFor(key, "m");

  /* Rewrite every id this mark defines, and every url(#..) that points at one. */
  const ids = [...svg.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]);
  for (const id of ids) {
    const scoped = `fm-${key}-${id}`;
    svg = svg.split(`id="${id}"`).join(`id="${scoped}"`);
    svg = svg.split(`url(#${id})`).join(`url(#${scoped})`);
    if (seenIds.has(scoped)) throw new Error(`id collision after scoping: ${scoped}`);
    seenIds.add(scoped);
  }

  /* Any url(#x) still pointing at an unscoped id means the defs and the
     reference disagree, and the mark would render without its gradient. */
  const dangling = [...svg.matchAll(/url\(#([^)]+)\)/g)]
    .map((m) => m[1])
    .filter((id) => !id.startsWith(`fm-${key}-`));
  if (dangling.length) {
    throw new Error(`mark "${key}" still references unscoped ids: ${dangling.join(", ")}`);
  }

  marks.push({ key, label, svg });
}

const body = marks
  .map(
    (m) =>
      `  {\n    key: ${JSON.stringify(m.key)},\n    label: ${JSON.stringify(m.label)},\n` +
      `    svg: ${JSON.stringify(m.svg)},\n  },`,
  )
  .join("\n");

writeFileSync(
  OUT,
  `/**
 * GENERATED by scripts/extract-marks.mjs — do not hand-edit.
 *
 * The eight trackable marks the demo's wall shows, lifted from the duotone
 * registry in public/v2/index.html so the React landing renders the same set
 * rather than a second drawing of it. Every id inside each SVG is prefixed
 * per mark: two of these on one page sharing a gradient id means the second
 * silently borrows the first's colours.
 *
 * Re-run the script if the demo's marks change.
 */
export interface ConsoleMark {
  key: string;
  label: string;
  /** Inline SVG. Trusted: it comes from this repo's own checked-in file. */
  svg: string;
}

export const CONSOLE_MARKS: ConsoleMark[] = [
${body}
];
`,
  "utf8",
);

const bytes = marks.reduce((n, m) => n + m.svg.length, 0);
console.log(
  `[marks] v ${marks.length} marks -> src/lib/console-marks.ts  ` +
    `(${(bytes / 1024).toFixed(1)} KB of svg, ${seenIds.size} ids scoped)`,
);
