#!/usr/bin/env node
/**
 * Pull the mockup's shelf — one product from each catalog — out of /v2.
 *
 * WHY THIS SET AND NOT THE HIGHEST SIX ON THIS SITE. The shelf that was here
 * picked the top-scoring item with a photograph from each of the landing's own
 * three catalogs, which produced two supplements, two whole foods and two
 * recipes. That is a fine shelf and it makes the wrong argument: six things
 * from three catalogs says "we score supplements and food". The mockup's shelf
 * is one item from EACH of six catalogs, and the argument is breadth — that a
 * capsule, a bottle of olive oil, a cleanser, a scale, a pair of dumbbells and
 * a sleep mask are all scored by the same product.
 *
 * The landing holds three of those six catalogs. The other three (personal
 * care, fitness gear, sleep gear) live in the web app, so the cards come from
 * the demo, which was built from those files.
 *
 * TWO OF THE SIX CARRY NO SCORE, AND THAT IS THE HONEST PART. A mask and a
 * mattress share no attribute one number could rank, so those catalogs compare
 * within a category instead and the cards show the price band the catalog
 * really holds. The note under the shelf is derived from the cards themselves,
 * so it cannot claim something the row does not show.
 *
 * IMAGES BECOME FILES. The demo carries them as base64 data URIs, which is
 * right for a single self-contained page and wrong for this one: inlined they
 * ride in the HTML on every load and cannot be cached separately.
 *
 *     node scripts/extract-shelf.mjs
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "public/v2/index.html");
const IMG_DIR = join(ROOT, "public/console-shelf");
const OUT = join(ROOT, "src/lib/console-shelf-cards.ts");

const html = readFileSync(SRC, "utf8");
const at = html.indexOf("window.CARDS");
if (at === -1) throw new Error("window.CARDS not found in public/v2/index.html");
const open = html.indexOf("[", at);
let depth = 0;
let end = open;
for (; end < html.length; end += 1) {
  if (html[end] === "[") depth += 1;
  else if (html[end] === "]") {
    depth -= 1;
    if (depth === 0) break;
  }
}
const cards = JSON.parse(html.slice(open, end + 1));

if (cards.length !== 6) throw new Error(`expected 6 cards, got ${cards.length}`);

mkdirSync(IMG_DIR, { recursive: true });

const out = cards.map((c) => {
  const m = /^data:image\/(\w+);base64,(.+)$/.exec(c.img ?? "");
  if (!m) throw new Error(`card "${c.k}" has no inline image`);
  const [, ext, b64] = m;
  const file = `${c.k}.${ext}`;
  writeFileSync(join(IMG_DIR, file), Buffer.from(b64, "base64"));

  if (c.score == null && !c.price) {
    throw new Error(`card "${c.k}" has neither a score nor a price band to show`);
  }
  return {
    key: c.k,
    catalog: c.cat,
    name: c.disp || c.name,
    brand: c.brand,
    meta: c.meta ?? null,
    score: typeof c.score === "number" ? c.score : null,
    price: c.price ?? null,
    /** How many items that catalog holds — the note reads these. */
    count: c.n ?? null,
    /** Built but not merged into the main catalog yet. */
    unmerged: Boolean(c.unmerged),
    /** Devices the catalog proposes rather than ships. */
    proposed: Boolean(c.proposed),
    image: `/console-shelf/${file}`,
  };
});

const scored = out.filter((c) => c.score != null).length;
writeFileSync(
  OUT,
  `/**
 * GENERATED by scripts/extract-shelf.mjs — do not hand-edit.
 *
 * One product from each of the six catalogs, as the mockup's shelf has them.
 * Images are written beside this as files under public/console-shelf.
 *
 * Two of the six carry no score on purpose: a mask and a mattress share no
 * attribute one number could rank, so those catalogs compare inside a category
 * and the card shows the price band the catalog actually holds.
 */
export interface ShelfCard {
  key: string;
  catalog: string;
  name: string;
  brand: string;
  meta: string | null;
  /** null where the catalog has no cross-category number. */
  score: number | null;
  /** Shown instead of a score, where there is none. */
  price: string | null;
  count: number | null;
  unmerged: boolean;
  proposed: boolean;
  image: string;
}

export const SHELF_CARDS: ShelfCard[] = ${JSON.stringify(out, null, 2)};
`,
  "utf8",
);

console.log(
  `[shelf] v ${out.length} cards (${scored} scored, ${out.length - scored} priced) ` +
    `-> src/lib/console-shelf-cards.ts, images in public/console-shelf/`,
);
console.log("        " + out.map((c) => `${c.catalog}: ${c.name}`).join("\n        "));
