#!/usr/bin/env node
/**
 * Pull the eight trackable marks out of the demo and into a module the React
 * landing can render.
 *
 * WHY GENERATED. The marks are the duotone set — sizeable inline SVG with
 * their own gradients and filters — and they already exist, once, inside
 * public/v2/index.html. Hand-copying eight of them into a .tsx would create a
 * second copy that looks identical on the day it is made and diverges from
 * then on, which is the failure this repo has a standing rule about. So this
 * reads the registry and writes the module, and running it again is how the
 * module gets fixed.
 *
 * THE ID PROBLEM. Each mark's <defs> uses short global ids (ca2, cb3, gs1).
 * Two SVGs sharing one id on a page means the second silently borrows the
 * first's gradient — a bug that renders as "some of the marks are the wrong
 * colour" and is almost impossible to read backwards. So every id is
 * rewritten with a per-mark prefix, and the script fails if any survive
 * unprefixed or if two marks still collide.
 *
 *     node scripts/extract-marks.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "public/v2/index.html");
const OUT = join(ROOT, "src/lib/console-marks.ts");

/** The wall, exactly as the demo builds it (its `WALL` array). */
const WALL = [
  ["capsule", "SUPPS"],
  ["meal", "MEALS"],
  ["glass", "WATER"],
  ["dumbbell", "TRAIN"],
  ["sauna", "SAUNA"],
  ["moon", "SLEEP"],
  ["cabin", "BODY"],
  ["care", "SKIN"],
];

/**
 * The rest of the registry.
 *
 * The wall is eight, the registry is fourteen, and the six that were not on
 * the wall were not extracted at all — so the streak block a few hundred
 * pixels below the wall rendered a raw 🔥 while `flame` sat drawn and unused
 * in the same file. Pulling only what one component happened to need is what
 * made an emoji look like the only option.
 *
 * These have no wall label because they are not on the wall; they are looked
 * up by key.
 */
const EXTRA = ["apple", "drop", "flame", "gem", "coffee", "bolt"];

const html = readFileSync(SRC, "utf8");
const start = html.indexOf("var MARKS = {");
if (start === -1) throw new Error("MARKS registry not found in public/v2/index.html");

/** Read one size's SVG string for a key out of the registry text. */
function svgFor(key, size) {
  const at = html.indexOf(`${key}: {`, start);
  if (at === -1) throw new Error(`mark "${key}" is not in the registry`);
  const re = new RegExp(`${size}:'((?:[^'\\\\]|\\\\.)*)'`, "g");
  re.lastIndex = at;
  const m = re.exec(html);
  if (!m || m.index > at + 40000) throw new Error(`mark "${key}" has no ${size}: entry`);
  return m[1];
}

const seenIds = new Set();
const marks = [];

for (const [key, label] of [...WALL, ...EXTRA.map((k) => [k, null])]) {
  /* "l", not "m". The demo's wall asks for data-sz="l" — an 86px box, where
     "m" is 38 — and taking the wrong one makes every mark look like a typo
     inside its tile. The size is part of the design, not a rendering detail. */
  let svg = svgFor(key, "l");

  /* Rewrite every id this mark defines, and every url(#..) that points at one. */
  const ids = [...svg.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]);
  for (const id of ids) {
    const scoped = `fm-${key}-${id}`;
    svg = svg.split(`id="${id}"`).join(`id="${scoped}"`);
    svg = svg.split(`url(#${id})`).join(`url(#${scoped})`);
    if (seenIds.has(scoped)) throw new Error(`id collision after scoping: ${scoped}`);
    seenIds.add(scoped);
  }

  /* Any url(#x) still pointing at an unscoped id means the defs and the
     reference disagree, and the mark would render without its gradient. */
  const dangling = [...svg.matchAll(/url\(#([^)]+)\)/g)]
    .map((m) => m[1])
    .filter((id) => !id.startsWith(`fm-${key}-`));
  if (dangling.length) {
    throw new Error(`mark "${key}" still references unscoped ids: ${dangling.join(", ")}`);
  }

  marks.push({ key, label, svg });
}

const body = marks
  .map(
    (m) =>
      `  {\n    key: ${JSON.stringify(m.key)},\n    label: ${JSON.stringify(m.label)},\n` +
      `    svg: ${JSON.stringify(m.svg)},\n  },`,
  )
  .join("\n");

const wallKeys = WALL.map(([k]) => k);

writeFileSync(
  OUT,
  `/**
 * GENERATED by scripts/extract-marks.mjs — do not hand-edit.
 *
 * All fourteen marks from the registry in public/v2/index.html, lifted rather
 * than redrawn so the React landing renders the same set the demo does. Every
 * id inside each SVG is prefixed per mark: two of these on one page sharing a
 * gradient id means the second silently borrows the first's colours.
 *
 * WHY ALL OF THEM, not just the wall's eight. The first version pulled only
 * what the wall needed, so \`flame\` was drawn, checked in, and unextracted —
 * and the streak block rendered a raw emoji a few hundred pixels under a wall
 * of hand-drawn marks. Extract the set; let components take what they want.
 *
 * Re-run the script if the demo's marks change.
 */
export interface ConsoleMark {
  key: string;
  /** The wall's caption, or null for a mark that is not on the wall. */
  label: string | null;
  /** Inline SVG. Trusted: it comes from this repo's own checked-in file. */
  svg: string;
}

export const CONSOLE_MARKS: ConsoleMark[] = [
${body}
];

/** Keyed lookup, for the one-off render sites. */
export const MARK_BY_KEY: Record<string, ConsoleMark> = Object.fromEntries(
  CONSOLE_MARKS.map((m) => [m.key, m]),
);

/** The wall, in the demo's own order. Not simply "the ones with a label" —
 *  order is part of the design and a filter would not preserve it. */
export const WALL_MARKS: ConsoleMark[] = ${JSON.stringify(wallKeys)}.map(
  (k) => MARK_BY_KEY[k],
);
`,
  "utf8",
);

const bytes = marks.reduce((n, m) => n + m.svg.length, 0);
console.log(
  `[marks] v ${marks.length} marks -> src/lib/console-marks.ts  ` +
    `(${(bytes / 1024).toFixed(1)} KB of svg, ${seenIds.size} ids scoped)`,
);
