#!/usr/bin/env node
/**
 * Pull the demo's blood panel out of /v2 and into a module section 03 renders.
 *
 * WHY GENERATED, like the marks: this data already exists once, in
 * public/v2/index.html, and a hand-typed second copy would agree with it on
 * the day it was made and quietly stop agreeing after. Re-running this is how
 * the module gets fixed.
 *
 * WHY DATA AND NOT A SCREENSHOT. Sections 01 and 02 show pictures of screens
 * the app actually has. There is no panel screen like the demo's in the
 * shipped app — /biomarkers is an upload prompt and a guide to getting drawn
 * — so a screenshot of the demo's `testing` screen would advertise a screen
 * that does not exist. The prototype's own section 03 does not use a
 * screenshot either; it renders these numbers as two cards, which is what
 * this feeds.
 *
 *     node scripts/extract-panel.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "public/v2/index.html");
const OUT = join(ROOT, "src/lib/console-panel.ts");

const html = readFileSync(SRC, "utf8");
const at = html.indexOf("window.PANEL = {");
if (at === -1) throw new Error("window.PANEL not found in public/v2/index.html");

/** Walk to the matching close brace so nested objects do not end it early. */
const open = html.indexOf("{", at);
let depth = 0;
let end = open;
for (; end < html.length; end += 1) {
  if (html[end] === "{") depth += 1;
  else if (html[end] === "}") {
    depth -= 1;
    if (depth === 0) break;
  }
}
const literal = html.slice(open, end + 1);

/* Our own checked-in file, evaluated to read an object literal that carries
   comments and trailing prose. Nothing here comes from outside the repo. */
const panel = new Function(`return (${literal});`)();

/** The strings hold HTML entities, because the demo writes them into innerHTML. */
const ENTITIES = {
  "&middot;": "·",
  "&rsquo;": "’",
  "&lsquo;": "‘",
  "&mdash;": "—",
  "&ndash;": "–",
  "&amp;": "&",
  "&nbsp;": " ",
};
function decode(v) {
  if (typeof v === "string") {
    let out = v;
    for (const [k, ch] of Object.entries(ENTITIES)) out = out.split(k).join(ch);
    /* An entity we do not know would ship as literal "&xyz;" on the page. */
    const left = out.match(/&[a-z]+;/gi);
    if (left) throw new Error(`undecoded entit${left.length > 1 ? "ies" : "y"}: ${left.join(", ")}`);
    return out;
  }
  if (Array.isArray(v)) return v.map(decode);
  if (v && typeof v === "object") {
    return Object.fromEntries(Object.entries(v).map(([k, x]) => [k, decode(x)]));
  }
  return v;
}

const clean = decode(panel);

if (!Array.isArray(clean.systems) || clean.systems.length < 5) {
  throw new Error(`expected the seven systems, got ${clean.systems?.length}`);
}
for (const s of clean.systems) {
  for (const f of ["k", "name", "score", "opt", "w", "d", "lead"]) {
    if (s[f] === undefined) throw new Error(`system "${s.k ?? "?"}" has no ${f}`);
  }
}

writeFileSync(
  OUT,
  `/**
 * GENERATED by scripts/extract-panel.mjs — do not hand-edit.
 *
 * The demo account's blood panel, lifted from public/v2/index.html so section
 * 03 renders the same numbers the demo does rather than a second copy of them.
 * Every number on the page is derived from \`systems\` — see console-panel.tsx
 * — so nothing shown can drift from the rows underneath it.
 *
 * These are an authored account, not a person. The page says so.
 */
export interface PanelSystem {
  k: string;
  name: string;
  /** Where this system is now, 0-100. */
  score: number;
  /** Where optimal is, 0-100. */
  opt: number;
  /** Its weight in the overall score. */
  w: number;
  /** Its move since the previous panel. */
  d: number;
  /** The markers behind it, in one line. */
  lead: string;
}

export interface PanelData {
  date: string;
  prev: string;
  markers: number;
  systems: PanelSystem[];
  acted: { k: string; did: string }[];
}

export const CONSOLE_PANEL: PanelData = ${JSON.stringify(clean, null, 2)};
`,
  "utf8",
);

console.log(
  `[panel] v ${clean.systems.length} systems, ${clean.markers} markers, ` +
    `${clean.acted?.length ?? 0} actions -> src/lib/console-panel.ts`,
);
